class CuboSemantico():
    def __init__(self):
        self.cubo = {
            "int" : {
                "int" : {
                    "+" : "int",
                    "-" : "int",
                    "*" : "int",
                    "/" : "int",
                    "=" : "int",
                    "==" : "bool",
                    "!=" : "bool",
                    ">" : "bool",
                    "<" : "bool",
                    ">=" : "bool",
                    "<=" : "bool",
                },
                "decimal" : {
                    "+" : "decimal",
                    "-" : "decimal",
                    "*" : "decimal",
                    "/" : "decimal",
                    "=" : "decimal",
                    "==" : "bool",
                    "!=" : "bool",
                    ">" : "bool",
                    "<" : "bool",
                    ">=" : "bool",
                    "<=" : "bool",
                },
                "bool" : {
                    "+" : "error",
                    "-" : "error",
                    "*" : "error",
                    "/" : "error",
                    "=" : "error",
                    "==" : "error",
                    "!=" : "error",
                    ">" : "error",
                    "<" : "error",
                    ">=" : "error",
                    "<=" : "error",
                },
                "string": {
                    "+": "error",
                    "-": "error",
                    "*": "error",
                    "/": "error",
                    "=": "error",
                    "==": "error",
                    "!=": "error",
                    ">": "error",
                    "<": "error",
                    ">=": "error",
                    "<=": "error",
                }
            },
            "decimal" : {
                "int" : {
                    "+" : "decimal",
                    "-" : "decimal",
                    "*" : "decimal",
                    "/" : "decimal",
                    "=" : "decimal",
                    "==" : "bool",
                    "!=" : "bool",
                    ">" : "bool",
                    "<" : "bool",
                    ">=" : "bool",
                    "<=" : "bool",
                },
                "decimal" : {
                    "+" : "decimal",
                    "-" : "decimal",
                    "*" : "decimal",
                    "/" : "decimal",
                    "=" : "decimal",
                    "==" : "bool",
                    "!=" : "bool",
                    ">" : "bool",
                    "<" : "bool",
                    ">=" : "bool",
                    "<=" : "bool",
                },
                "bool" : {
                    "+" : "error",
                    "-" : "error",
                    "*" : "error",
                    "/" : "error",
                    "=" : "error",
                    "==" : "error",
                    "!=" : "error",
                    ">" : "error",
                    "<" : "error",
                    ">=" : "error",
                    "<=" : "error",
                },
                "string": {
                    "+": "error",
                    "-": "error",
                    "*": "error",
                    "/": "error",
                    "=": "error",
                    "==": "error",
                    "!=": "error",
                    ">": "error",
                    "<": "error",
                    ">=": "error",
                    "<=": "error",
                }
            },
            "bool" : {
                "int" : {
                    "+" : "error",
                    "-" : "error",
                    "*" : "error",
                    "/" : "error",
                    "=" : "error",
                    "==" : "error",
                    "!=" : "error",
                    ">" : "error",
                    "<" : "error",
                    ">=" : "error",
                    "<=" : "error",
                },
                "decimal" : {
                    "+" : "error",
                    "-" : "error",
                    "*" : "error",
                    "/" : "error",
                    "=" : "error",
                    "==" : "error",
                    "!=" : "error",
                    ">" : "error",
                    "<" : "error",
                    ">=" : "error",
                    "<=" : "error",
                },
                "bool" : {
                    "+" : "error",
                    "-" : "error",
                    "*" : "error",
                    "/" : "error",
                    "=" : "bool",
                    "==" : "bool",
                    "!=" : "bool",
                    ">" : "error",
                    "<" : "error",
                    ">=" : "error",
                    "<=" : "error",
                },
                "string": {
                    "+": "error",
                    "-": "error",
                    "*": "error",
                    "/": "error",
                    "=": "error",
                    "==": "error",
                    "!=": "error",
                    ">": "error",
                    "<": "error",
                    ">=": "error",
                    "<=": "error",
                }
            },
            "string": {
                "int": {
                    "+": "error",
                    "-": "error",
                    "*": "error",
                    "/": "error",
                    "=": "error",
                    "==": "error",
                    "!=": "error",
                    ">": "error",
                    "<": "error",
                    ">=": "error",
                    "<=": "error",
                },
                "decimal": {
                    "+": "error",
                    "-": "error",
                    "*": "error",
                    "/": "error",
                    "=": "error",
                    "==": "error",
                    "!=": "error",
                    ">": "error",
                    "<": "error",
                    ">=": "error",
                    "<=": "error",
                },
                "bool": {
                    "+": "error",
                    "-": "error",
                    "*": "error",
                    "/": "error",
                    "=": "error",
                    "==": "error",
                    "!=": "error",
                    ">": "error",
                    "<": "error",
                    ">=": "error",
                    "<=": "error",
                },
                "string": {
                    "+": "string",
                    "-": "error",
                    "*": "error",
                    "/": "error",
                    "=": "string",
                    "==": "bool",
                    "!=": "bool",
                    ">": "error",
                    "<": "error",
                    ">=": "error",
                    "<=": "error",
                }
            }
        }

    def Tipo(self, operadorTipoIzq, operadorTipoDer, operador):
        return self.cubo[operadorTipoIzq][operadorTipoDer][operador]
